version: "2"

services:
  upload:
    image: ${REGISTRY_URL}/pmis-fileupload
    extends:
      service: logging
    volumes:
    - ${TEMP_PATH}:/tmp
    - ngx:/etc/nginx/www

  php:
    image: php:5.6-fpm
    extends:
      service: logging
    volumes:
    - ngx:/etc/nginx/www
    environment:
    - LOGSPOUT=ignore

  hub:
    extends:
      service: logging
    environment:
    - LOGSPOUT=ignore
    volumes: 
    - ${LOG_PATH}:/var/log/nginx
    - ${SSL_HOME}:${SSL_HOME}
    - ./conf.d:/usr/share/nginx/vhosts/
    - ./html:/usr/share/nginx/html
    - ${HTPASSWD_PATH}:/usr/share/nginx/conf.d/.htpasswd

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"