version: "2"

services: 

  nginx:
    image: sangah/nginx-base
    volumes: 
    - ./html:/usr/share/nginx/html
    - ./conf.d:/usr/share/nginx/conf.d
    networks: 
      default:
      hub_net:
        aliases:
        - sample

  php:
    image: php:5.6-fpm
    volumes:
    - ./html:/usr/share/nginx/html
    networks:
      default:
        aliases:
        - samplephp

networks: 
  hub_net:
    external: true